Translation PT-BR
microsoft/workshop-library pull request #158
Opened 2022-08-12 13:33 UTC by oberdansch

Translation of public speaking readme to pt-br

## Use this template to add a workshop to this repo. Add the following items:

- [ ] Your workshop design document, filled in with some details about your proposed workshop including its title and the three stages in the designer delineated, using the `workshop-designer.md` file in the template.

- [ ] A `README.md` file that describes the steps of the workshop. 

- [ ] Powerpoint Slides for the workshop.

- [ ] The workshop's solution in the `/solution` folder.

- [ ] An embedded Train the Trainer video.

- [ ] A Call to Action to enhance the workshop with a direct line to Microsoft Learn by linking to an appropriate Learn module.

- [ ] Code quality check: no authentication keys should be included in solution or sample code

A reviewer will be assigned to the workshop and will work with you to shape it for production. Thank you for your contribution!

2022-08-15 13:28 UTC, PabloNunes approved these changes

2022-08-15 14:21 UTC, alfredodeza requested changes

2022-08-15 14:21 UTC, alfredodeza commented on short/public-speaking/translations/README.md
> +- [Portuguese (BR)](./pt-br/README.pt.md)
This link is not correct. 
```suggestion
- [Portuguese (BR)](./pt-br/README.md)
```

2022-08-16 18:49 UTC, alfredodeza approved these changes

2022-08-16 18:49 UTC, merged