#174 Spanish Translations - Regression Models R
microsoft/workshop-library pull request #194
Opened 2022-11-23 03:30 UTC by jona866

Translation folder
- List with existing translations
- Folder with the Spanish translation
    - README
    - slide.ppt

2022-11-23 06:46 UTC, jona866 commented
@microsoft-github-policy-service agree [company="jona866"]

2022-11-23 06:48 UTC, jona866 commented
@microsoft-github-policy-service agree company="jona866"

2022-11-29 18:52 UTC, abrilurena requested changes
¡Muchas gracias por todo tu tiempo y ayuda, @jona866! ❤️ ✨ Hice algunos comentarios, me puedes preguntar si tienes alguna duda. 

Sobre las diapositivas, ¡me parecen geniales! muy buena traducción ❤️ estaría genial si pudieras ayudarme a traducir el contenido que viene en las _notas de cada diapositiva_ y cambiar "llame" a "llama" en los slides 17 y 18, por favor 🙏 te lo agradeceria muchisimo
 
<img width="976" alt="image" src="https://user-images.githubusercontent.com/107883174/204619963-59436bff-83fb-4200-b65e-57915eef7f6d.png">

2022-12-12 18:22 UTC, abrilurena requested changes
¡Muchas gracias @jona866 por toda tu ayuda! Ya solo queda pendiente las traducciones de las notas que se encuentran en los slides 😄 Cualquier duda me puedes preguntar 😄 ❤️

2023-01-05 21:47 UTC, abrilurena commented
¡Muchas gracias @jona866! Ya termine de revisar las notas de las diapositivas, estas son mis ultimas sugerencias y comentarios :D 

- Slide # 5 : creo que estaria mejor cambiar "alquilar"/ "alquileres" a "renta" y "rentas", que opinas?
<img width="1248" alt="image" src="https://user-images.githubusercontent.com/107883174/210629653-fc862d62-3597-4ec6-9857-cf413049936e.png">

- Slide # 8 : creo que estaría bien aclarar que MSE es Mean Squared Error porque creo que se podrían confundir las personas. 
<img width="524" alt="image" src="https://user-images.githubusercontent.com/107883174/210652462-2d81aeb2-aa44-4daa-ac0d-0ae9d596e93d.png">

- slide # 10:  creo que estaría bien mantener en paréntesis el significado en ingles de algoritmos o métodos de conjunto (ensemble algorithms) por lo mismo que se podrían confundir las otras personas, qué opinas? 👀 
<img width="1198" alt="image" src="https://user-images.githubusercontent.com/107883174/210672591-9818eceb-6fac-4e7c-85ad-c8481345ed8f.png">

- slide # 13: encontre estos pequeños detalles de ortografia :D 
<img width="832" alt="image" src="https://user-images.githubusercontent.com/107883174/210884779-59ec7389-08f8-4e04-9039-8687051b8cfe.png">

2023-01-05 23:05 UTC, jona866 commented
¡Listo! También corregí la ubicación de los archivos :)

2023-01-05 23:07 UTC, abrilurena approved these changes
¡Mil gracias por toda tu ayuda y tiempo @jona866! Ya se subirán tus cambios al main branch :D ✨ 🚀 eres el primer pull request aceptado en este año 😃

2023-01-05 23:07 UTC, merged